## ROS OpenCV performance exemples

### Open and save Image files

There is an exemple to open and copy an image from a PC folder "images":

In [ ]:
python open_copy.py

In [1]:
#!/usr/bin/env python

#import numpy: the data structure that will handle an image
import numpy as np

#import openCV
import cv2
 

image_name = "flower"

print ('read an image from file')
img = cv2.imread("images/"+image_name+".jpg")

print ('create a window holder for the image')
cv2.namedWindow("Image",cv2.WINDOW_NORMAL)

print ('display the image')
cv2.imshow("Image",img)

print ('press a key inside the image to make a copy')
cv2.waitKey(0)

print ('image copied to folder images/copy/')
cv2.imwrite("images/copy/"+image_name+"-copy.jpg",img)

read an image from file
create a window holder for the image
display the image
press a key inside the image to make a copy
image copied to folder images/copy/


False

### Pixels and Image structure

Take the following "image_structure.py" python script to see the structure of an image

[Image Structure Notebook](./Image_Structure.ipynb)

In [2]:
#!/usr/bin/env python

#import numpy: the data structure that will handle an image
import numpy as np

#import openCV
import cv2

image_name = "blackwhite"

print ('read an image from file')
img = cv2.imread("images/"+image_name+".jpg")

print ('display the content of the image')
print (img)
print ('In Python, an image is stored in a numpy array. Numpy is library used for scientific computing of multi-dimensional arrays and matrices.')

print ('we can determine several features of the images using numpy array properties')
print ('type of an image type(img): %s'%type(img))
print ('size of the image img.size: %d'%img.size)
print ('length of the image (number of pixel in the vertical direction) len(img): %d'%len(img))
print ('shape of an image (length in pixe, width in pixel, number of color) img.shape (%d,%d,%d)'%img.shape)
print ('image length (also height) img.shape[0]: %d'%img.shape[0])
print ('image width img.shape[1]: %d'%img.shape[1])

height, width, channels = img.shape
print ('height = %d'%height)
print ('width = %d'%width)
print ('channels = %d'%channels)

print ('number of colors per pixel img.shape[2]: %d'%img.shape[2])
print ('number of pixels: %d'%(img.shape[0]*img.shape[1]))
print ('type of the image img.dtype: %s'%img.dtype)
print ('sub-image at row [10] (img[10])')
print (img[10])
print ('shape of sub-image at row [0] (img[10].shape)')
print (img[10].shape)
print ('pixel at raw 10 and column 5 (img[10, 5])')
print (img[10, 5])
print (img[10] [5])
print ('pixel at raw 0 and column 0 (img[0, 0])')
print (img[0, 0])
print (img[0] [0])

print ('you can see a single channel in the image, for example only the first channel')
print (img[:, :, 0])

read an image from file
display the content of the image
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [  0   0   0]
  [  0   0   0]
  [  2   2   2]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [  0   0   0]
  [  0   0   0]
  [  2   2   2]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [  0   0   0]
  [  0   0   0]
  [  2   2   2]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [  0   0   0]
  [  1   1   1]
  [  3   3   3]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [  0   0   0]
  [  1   1   1]
  [  3   3   3]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [  0   0   0]
  [  1   1   1]
  [  3   3   3]]]
In Python, an image is stored in a numpy array. Numpy is library used for scientific computing of multi-dimensional arrays and matrices.
we can determine several features of the images using numpy array properties
type of an image type(img): <class 'numpy.ndarray'>
size of the image img.size: 1350
length of the 

### Image encoding

There are 3 different encodings:

- grayscale
- Red-Green_Blue (RGB)
- Hue (color in 36º), Saturation, Value (brightness)(HSV)

Let's see the "image_encoding.py" file

In [1]:
#!/usr/bin/env python 

import numpy as np
import cv2


image_name = "tree"

print ('read an image from file')
color_image = cv2.imread("images/tree.jpg",cv2.IMREAD_COLOR)

print ('display image in native color')
cv2.imshow("Original Image",color_image)
cv2.moveWindow("Original Image",0,0)
print(color_image.shape)

height,width,channels = color_image.shape

print ('slipt the image into three channels.')
blue,green,red = cv2.split(color_image)

cv2.imshow("Blue Channel",blue)
cv2.moveWindow("Blue Channel",0,height)

cv2.imshow("Red Channel",red)
cv2.moveWindow("Red Channel",0,height)

cv2.imshow("Greeen Channel",green)
cv2.moveWindow("Green Channel",0,height)


# Hue: indicates the type of color that we see in a 360 degree format.
# Saturation: an indication of how saturated an individual color is 
# Value: indicates how luminous the channel is. 

print ('---- slipt the image into Hue, Saturation, Value channels.----- ')
hsv = cv2.cvtColor(color_image, cv2.COLOR_BGR2HSV)
h,s,v = cv2.split(hsv)
hsv_image = np.concatenate((h,s,v),axis=1)
cv2.imshow("Hue, Saturation, Value Image",hsv_image)
cv2.imshow("HSV Image",hsv)


print ('------ converts an image to a grayscale ------')
gray_image = cv2.cvtColor(color_image, cv2.COLOR_BGR2GRAY)
cv2.imshow("Gray Image ",gray_image)
 
print (gray_image)

cv2.waitKey(0)
cv2.destroyAllWindows()

read an image from file
display image in native color
(293, 220, 3)
slipt the image into three channels.
---- slipt the image into Hue, Saturation, Value channels.----- 
------ converts an image to a grayscale ------
[[214 213 213 ... 139 139 139]
 [215 214 213 ... 139 139 139]
 [215 214 213 ... 141 141 141]
 ...
 [ 50  42  29 ...  52  45  58]
 [ 57  57  43 ...  70  69  72]
 [ 62  69  58 ...  92  98  94]]


### Video Stream

Consider the "read_video.py" file and make changes for video from USB camera:

In [1]:
#!/usr/bin/env python 
import numpy as np
import cv2

#video_capture = cv2.VideoCapture(0)
video_capture = cv2.VideoCapture('video/ros.mp4')

while(True):
    ret, frame = video_capture.read()
    if ret:
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        frame = cv2.resize(frame, (0,0), fx=0.5,fy=0.5)
        cv2.line(frame,(0,0),(511,511),(255,0,0),5)
        cv2.imshow("Frame",frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

video_capture.release()
cv2.destroyAllWindows()

### Drawing Shapes

run the "image_draw.py" file

In [1]:

#!/usr/bin/env python 

import numpy as np
import cv2


image = np.zeros((512,512,3), np.uint8)

#cv2.circle(image, (image.shape[0]/2, image.shape[1]/2),63, (255,255,255), 5)
cv2.line(image,(0,0),(511,511),(255,255,255),5)

cv2.rectangle(image,(384,0),(510,128),(0,255,0),3)
cv2.ellipse(image,(256,256),(100,50),0,0,180,255,-1)

pts = np.array([[10,5],[20,30],[70,20],[50,10]], np.int32)
pts = pts.reshape((-1,1,2))
cv2.polylines(image,[pts],True,(0,255,255))

font = cv2.FONT_HERSHEY_SIMPLEX
#cv2.putText(image,'ROS, OpenCV',(10,500), font, 2,(255,255,255),2,cv2.LINE_AA)
cv2.putText(image,'OpenCV',(10,500), font, 4,(255,255,255),2)
cv2.imshow("Image Panel",image)

cv2.waitKey(0)
cv2.destroyAllWindows()

### Color Filtering

In [ ]:
import numpy as np
import cv2

image = cv2.imread("images/tennisball05.jpg")
cv2.imshow("Original",image)

#convert the image into the HSV color space
hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
cv2.imshow("hsv image",hsv)

#find the upper and lower bounds of the yellow color (tennis ball)
yellowLower =(30, 150, 100)
yellowUpper = (50, 255, 255)

#define a mask using the lower and upper bounds of the yellow color 
mask = cv2.inRange(hsv, yellowLower, yellowUpper)

cv2.imshow("mask image", mask)

cv2.waitKey(0)
cv2.destroyAllWindows()



cv2.waitKey(0)
cv2.destroyAllWindows()

### Image Thresholding

In [1]:
import numpy as np
import cv2


def read_image(image_name, as_gray):
    if as_gray: 
        image = cv2.imread(image_name,cv2.IMREAD_GRAYSCALE)
    else:
        image = cv2.imread(image_name,cv2.IMREAD_COLOR)
    cv2.imshow("Image",image)
    return image



def basic_thresholding(gray_image, threshol_value):
    ret, thresh_basic = cv2.threshold(gray_image,
                                    threshol_value,
                                    255,
                                    cv2.THRESH_BINARY_INV)
    cv2.imshow("Basic Binary Image",thresh_basic)

def adaptive_thresholding(gray_image, threshol_value):
    adaptive_threshold_image = cv2.adaptiveThreshold(gray_image, 
                                        255, 
                                        cv2.ADAPTIVE_THRESH_MEAN_C, 
                                        cv2.THRESH_BINARY_INV, 
                                        threshol_value, 
                                        2)
    cv2.imshow("Adaptive Threshold Image",adaptive_threshold_image)


def main():
    #image_name = "images/shapes.png"
    image_name = "images/tomato.jpg"
    as_gray = True
    threshol_value=115
    gray_image = read_image(image_name,as_gray)
    basic_thresholding(gray_image, threshol_value)
    adaptive_thresholding(gray_image, threshol_value)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

if __name__ == '__main__':
    main()

### Countours Detection

In [1]:
import numpy as np
import cv2

def read_rgb_image(image_name, show):
    rgb_image = cv2.imread(image_name)
    if show: 
        cv2.imshow("RGB Image",rgb_image)
    return rgb_image

def convert_rgb_to_gray(rgb_image,show):
    gray_image = cv2.cvtColor(rgb_image, cv2.COLOR_BGR2GRAY)
    if show: 
        cv2.imshow("Gray Image",gray_image)
    return gray_image

def convert_gray_to_binary(gray_image, adaptive, show):
    if adaptive: 
        binary_image = cv2.adaptiveThreshold(gray_image, 
                            255, 
                            cv2.ADAPTIVE_THRESH_GAUSSIAN_C, 
                            cv2.THRESH_BINARY_INV, 115, 2)
    else:
        _,binary_image = cv2.threshold(gray_image,127,255,cv2.THRESH_BINARY_INV)
    if show:
        cv2.imshow("Binary Image", binary_image)
    return binary_image    

def getContours(binary_image):      
    contours, hierarchy = cv2.findContours(binary_image, 
                                              cv2.RETR_TREE, 
                                               cv2.CHAIN_APPROX_SIMPLE)
    return contours

def draw_contours(image, contours, image_name):
    index = -1 #means all contours
    thickness = 2 #thinkess of the contour line
    color = (255, 0, 255) #color of the contour line
    cv2.drawContours(image, contours, index, color, thickness)
    cv2.imshow(image_name,image)



def main():
    image_name = "images/tomato.jpg"
    rgb_image = read_rgb_image(image_name, True)
    gray_image= convert_rgb_to_gray(rgb_image,True)
    binary_image = convert_gray_to_binary(gray_image, True, True)
    contours = getContours(binary_image)
    draw_contours(rgb_image, contours,"RGB Contours")

    cv2.waitKey(0)
    cv2.destroyAllWindows()

if __name__ == '__main__':
    main()


### Contours Processing

In [ ]:
import numpy as np
import cv2

def read_rgb_image(image_name, show):
    rgb_image = cv2.imread(image_name)
    if show: 
        cv2.imshow("RGB Image",rgb_image)
    return rgb_image

def convert_rgb_to_gray(rgb_image,show,blur):
    gray_image = cv2.cvtColor(rgb_image, cv2.COLOR_BGR2GRAY)
    if show: 
        cv2.imshow("Gray Image",gray_image)
    if blur: rgb_image = cv2.GaussianBlur(rgb_image, (5, 5), 0)
    return gray_image

def convert_gray_to_binary(gray_image, adaptive, show):
    #choose THRESH_BINARY_INV or THRESH_BINARY depending on
    # which give a black background. 
    # We must get a black background for countours to work 
    if adaptive: 
        binary_image = cv2.adaptiveThreshold(gray_image, 
                            255, 
                            cv2.ADAPTIVE_THRESH_GAUSSIAN_C, 
                            cv2.THRESH_BINARY_INV, 5, 2)
    else:
        _,binary_image = cv2.threshold(gray_image,60,255,cv2.THRESH_BINARY_INV)
    if show:
        cv2.imshow("Binary Image", binary_image)
    #binary_image = cv2.erode(binary_image, None, iterations=2)
    #binary_image = cv2.dilate(binary_image, None, iterations=2)
    return binary_image    

def getContours(binary_image):      
    #contours, hierarchy = cv2.findContours(binary_image, 
    #                                          cv2.RETR_TREE, 
    #                                           cv2.CHAIN_APPROX_SIMPLE)
    contours, hierarchy = cv2.findContours(binary_image.copy(), 
                                            cv2.RETR_EXTERNAL,
                                           cv2.CHAIN_APPROX_SIMPLE)
    return contours

def draw_contours(image, contours, image_name):
    index = -1 #means all contours
    thickness = 2 #thinkess of the contour line
    color = (255, 0, 255) #color of the contour line
    cv2.drawContours(image, contours, index, color, thickness)
    cv2.imshow(image_name,image)

def process_contours(binary_image, rgb_image, contours):
    black_image = np.zeros([binary_image.shape[0], binary_image.shape[1],3],'uint8')
    
    for c in contours:
        area = cv2.contourArea(c)
        perimeter= cv2.arcLength(c, True)
        ((x, y), radius) = cv2.minEnclosingCircle(c)
        cv2.drawContours(rgb_image, [c], -1, (150,250,150), 1)
        cv2.drawContours(black_image, [c], -1, (150,250,150), 1)
        cx, cy = get_contour_center(c)
        cv2.circle(rgb_image, (cx,cy),(int)(radius),(0,0,255),1)
        cv2.circle(black_image, (cx,cy),(int)(radius),(0,0,255),1)
        print ("Area: {}, Perimeter: {}".format(area, perimeter))
    print ("number of contours: {}".format(len(contours)))
    cv2.imshow("RGB Image Contours",rgb_image)
    cv2.imshow("Black Image Contours",black_image)

def get_contour_center(contour):
    M = cv2.moments(contour)
    cx=-1
    cy=-1
    if (M['m00']!=0):
        cx= int(M['m10']/M['m00'])
        cy= int(M['m01']/M['m00'])
    return cx, cy

def main():
    image_name = "images/shapes.png"
    #image_name = "images/shapes2.jpg"
    rgb_image = read_rgb_image(image_name, True)
    gray_image= convert_rgb_to_gray(rgb_image,True,True)
    binary_image = convert_gray_to_binary(gray_image, True, True)
    contours = getContours(binary_image)
    process_contours(binary_image, rgb_image,contours)

    cv2.waitKey(0)
    cv2.destroyAllWindows()

if __name__ == '__main__':
    main()



cv2.waitKey(0)
cv2.destroyAllWindows()

Area: 10682.5, Perimeter: 386.91882729530334
Area: 5091.0, Perimeter: 340.0487701892853
Area: 7745.0, Perimeter: 354.8284270763397
Area: 5411.0, Perimeter: 296.4995696544647
Area: 16340.5, Perimeter: 519.899494767189
number of contours: 5


### Ball Detection

In [ ]:
import numpy as np
import cv2

def read_rgb_image(image_name, show):
    rgb_image = cv2.imread(image_name)
    if show: 
        cv2.imshow("RGB Image",rgb_image)
    return rgb_image

def filter_color(rgb_image, lower_bound_color, upper_bound_color):
    #convert the image into the HSV color space
    hsv_image = cv2.cvtColor(rgb_image, cv2.COLOR_BGR2HSV)
    cv2.imshow("hsv image",hsv_image)

    #find the upper and lower bounds of the yellow color (tennis ball)
    yellowLower =(30, 150, 100)
    yellowUpper = (50, 255, 255)

    #define a mask using the lower and upper bounds of the yellow color 
    mask = cv2.inRange(hsv_image, lower_bound_color, upper_bound_color)

    return mask

def getContours(binary_image):      
    contours, hierarchy = cv2.findContours(binary_image.copy(), 
                                            cv2.RETR_EXTERNAL,
                                           cv2.CHAIN_APPROX_SIMPLE)
    return contours


def draw_ball_contour(binary_image, rgb_image, contours):
    black_image = np.zeros([binary_image.shape[0], binary_image.shape[1],3],'uint8')
    
    for c in contours:
        area = cv2.contourArea(c)
        perimeter= cv2.arcLength(c, True)
        ((x, y), radius) = cv2.minEnclosingCircle(c)
        if (area>100):
            cv2.drawContours(rgb_image, [c], -1, (150,250,150), 1)
            cv2.drawContours(black_image, [c], -1, (150,250,150), 1)
            cx, cy = get_contour_center(c)
            cv2.circle(rgb_image, (cx,cy),(int)(radius),(0,0,255),1)
            cv2.circle(black_image, (cx,cy),(int)(radius),(0,0,255),1)
            cv2.circle(black_image, (cx,cy),5,(150,150,255),-1)
            print ("Area: {}, Perimeter: {}".format(area, perimeter))
    print ("number of contours: {}".format(len(contours)))
    cv2.imshow("RGB Image Contours",rgb_image)
    cv2.imshow("Black Image Contours",black_image)

def get_contour_center(contour):
    M = cv2.moments(contour)
    cx=-1
    cy=-1
    if (M['m00']!=0):
        cx= int(M['m10']/M['m00'])
        cy= int(M['m01']/M['m00'])
    return cx, cy

def main():
    image_name = "images/tennisball05.jpg"
    yellowLower =(30, 150, 100)
    yellowUpper = (50, 255, 255)
    rgb_image = read_rgb_image(image_name, True)
    binary_image_mask = filter_color(rgb_image, yellowLower, yellowUpper)
    contours = getContours(binary_image_mask)
    draw_ball_contour(binary_image_mask, rgb_image,contours)

    cv2.waitKey(0)
    cv2.destroyAllWindows()

if __name__ == '__main__':
    main()



cv2.waitKey(0)
cv2.destroyAllWindows()

Area: 818.5, Perimeter: 163.9827550649643
number of contours: 5


### Ball Tracking

In [ ]:
import numpy as np
import cv2
import time

def read_rgb_image(image_name, show):
    rgb_image = cv2.imread(image_name)
    if show: 
        cv2.imshow("RGB Image",rgb_image)
    return rgb_image

def filter_color(rgb_image, lower_bound_color, upper_bound_color):
    #convert the image into the HSV color space
    hsv_image = cv2.cvtColor(rgb_image, cv2.COLOR_BGR2HSV)
    cv2.imshow("hsv image",hsv_image)

    #define a mask using the lower and upper bounds of the yellow color 
    mask = cv2.inRange(hsv_image, lower_bound_color, upper_bound_color)

    return mask


    

def getContours(binary_image):     
    #_, contours, hierarchy = cv2.findContours(binary_image, 
    #                                          cv2.RETR_TREE, 
    #                                           cv2.CHAIN_APPROX_SIMPLE)
    contours, hierarchy = cv2.findContours(binary_image.copy(), 
                                            cv2.RETR_EXTERNAL,
                                           cv2.CHAIN_APPROX_SIMPLE)
    return contours


def draw_ball_contour(binary_image, rgb_image, contours):
    black_image = np.zeros([binary_image.shape[0], binary_image.shape[1],3],'uint8')
    
    for c in contours:
        area = cv2.contourArea(c)
        perimeter= cv2.arcLength(c, True)
        ((x, y), radius) = cv2.minEnclosingCircle(c)
        if (area>3000):
            cv2.drawContours(rgb_image, [c], -1, (150,250,150), 1)
            cv2.drawContours(black_image, [c], -1, (150,250,150), 1)
            cx, cy = get_contour_center(c)
            cv2.circle(rgb_image, (cx,cy),(int)(radius),(0,0,255),1)
            cv2.circle(black_image, (cx,cy),(int)(radius),(0,0,255),1)
            cv2.circle(black_image, (cx,cy),5,(150,150,255),-1)
            #print ("Area: {}, Perimeter: {}".format(area, perimeter))
    #print ("number of contours: {}".format(len(contours)))
    cv2.imshow("RGB Image Contours",rgb_image)
    cv2.imshow("Black Image Contours",black_image)

def get_contour_center(contour):
    M = cv2.moments(contour)
    cx=-1
    cy=-1
    if (M['m00']!=0):
        cx= int(M['m10']/M['m00'])
        cy= int(M['m01']/M['m00'])
    return cx, cy

def detect_ball_in_a_frame(image_frame):
    yellowLower =(30, 100, 50)
    yellowUpper = (60, 255, 255)
    rgb_image = image_frame
    binary_image_mask = filter_color(rgb_image, yellowLower, yellowUpper)
    contours = getContours(binary_image_mask)
    draw_ball_contour(binary_image_mask, rgb_image,contours)



def main():
    #video_capture = cv2.VideoCapture(0)
    video_capture = cv2.VideoCapture('video/tennis-ball-video.mp4')

    while(True):
        ret, frame = video_capture.read()
        detect_ball_in_a_frame(frame)
        time.sleep(0.033)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cv2.waitKey(0)
    cv2.destroyAllWindows()

if __name__ == '__main__':
    main()



cv2.waitKey(0)
cv2.destroyAllWindows()

## Exercise:

* Add a Red Ball in your scenario.
* Navigate through you world
* Write a Python node with the folowing behaviour:
    * Navigate until the camera can detect the ball
    * Take an image and store it.
    * Stop the robot

* More Tips and helps
    * [Shape Detection](https://www.pyimagesearch.com/2016/02/08/opencv-shape-detection/)
    * [Ball Tracking with trajectory](https://www.pyimagesearch.com/2015/09/14/ball-tracking-with-opencv/)
    * [HSV color picker (in opencv H value goes from 0 to 179)](https://alloyui.com/examples/color-picker/hsv.html)
    * [The Construct Live Class How to Use OpenCV](https://www.youtube.com/watch?v=0C0gOsLoP9k)